variables:
  IMAGE_NAME: samandarali777/medical_reception_service
  IMAGE_TAG: latest

stages:
  - build
  - deploy

build-image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:  
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - prod

deploy:
  stage: deploy
  before_script:
   - chmod 400 $SSH_KEY
  script:
   - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$SERVER_IP "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS && 
        docker stop reception_service ||  true &&
        docker rm reception_service || true &&
        docker image rm $IMAGE_NAME || true &&
        docker run --name reception_service -d -p 5000:5000 --network postgres_default $IMAGE_NAME:$IMAGE_TAG"
  only:
    - prod 